# Generated by Django 5.2.17 on 2026-09-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsection',
            name='faculty',
        ),
        migrations.AddField(
            model_name='classsection',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='assigned_classes', to='employees.userprofile'),
        ),
    ]
