# Generated by Django 5.2.17 on 2026-09-19 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_classsection_faculty_classsection_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employees.classsection'),
        ),
    ]
