# Generated by Django 5.2.17 on 2026-09-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_task_class_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
    ]
