# Generated by Django 5.2.17 on 2026-09-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_leaverequest_employee_leaverequest_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='FACULTY', max_length=20),
        ),
    ]
